== Release Instructions

Create a new release using the GitHub UI (which will automatically create a tag). There is no need to change master during release. Please keep releases to form `vX` where `v` is always a `v` and `X` is the release number.

. Navigate to the releases page: https://github.com/fabric8-launcher/launcher-booster-catalog/releases
. Click in `Draft a new Release`
.. Check if a draft release doesn't already exist first - see the Optional step below
. Tag the release following the pattern `vX` where `v` is always a `v` and `X` is the release number.
. Choose the specific commit you want to release (or use master)
. Click `Publish Release` to immediately update production
. (Optional) Create a new draft release with the next version
.. This will save you from having to remember the next version name next time you release the catalog

== How to make the release effective in production?

The release will be automatically effective in production once it is published. Saving as a Draft or publishing pre-release builds do not affect production. 

In short, if you don't want the release to be effective in production immediately, then make sure that the `This is a pre-release` checkbox is marked.
